comment_width = 75
edition = "2021"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
match_arm_leading_pipes = "Always"
max_width = 75
merge_derives = false
reorder_impl_items = true
tab_spaces = 4
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
