[package]
name = "resworb"
version = "0.1.0"
license-file = "./LICENSE"
edition = "2021"

[workspace]
members = [
    "html"
]

[[bin]]
name = "resworb"
path = "./resworb.rs"

[dependencies]
html = { path = "html", package = "resworb-html" }
