[package]
name = "resworb-css-parser"
version = "0.1.23"
license-file = "../LICENSE"
edition = "2021"

[lib]
path = "./lib.rs"

[dependencies]
infra = { path = "../../infra", package = "resworb-infra" }
parser = { path = "../../parser", package = "resworb-parser" }
