[package]
name = "resworb-parser"
version = "0.1.15"
license-file = "../LICENSE"
edition = "2021"

[lib]
path = "./lib.rs"

[dependencies]
infra = { path = "../infra", package = "resworb-infra" }
# syntax = { version = "^0.15", package = "rowan" }
