[package]
name = "resworb-html"
version = "0.1.0"
license-file = "../LICENSE"
edition = "2021"

[lib]
path = "./lib.rs"

[dependencies]
parser = { path = "./parser", package = "resworb-html-parser" }
