[package]
name = "resworb-dom"
version = "0.1.3"
license-file = "../LICENSE"
edition = "2021"

[lib]
path = "./lib.rs"

[dependencies]
infra = { path = "../infra", package = "resworb-infra" }
html-elements = { path = "../html/elements", package = "resworb-html-elements" }
